Warn if using a remote source matches your local dotfiles.
Closes #46.

diff --git a/bin/fresh b/bin/fresh
--- a/bin/fresh
+++ b/bin/fresh
@@ -102,6 +102,28 @@ _repo_name() {
 _prepare_file_source() {
   # clone or update source repo
   if [ -n "$REPO_NAME" ]; then
+    if [ -d "$FRESH_LOCAL/.git" ] && [ -z "$FRESH_NO_LOCAL_CHECK" ]; then
+      if [ -z "$LOCAL_REPO_URL" ]; then
+        LOCAL_REPO_URL="$(cd "$FRESH_LOCAL" && git config --get remote.origin.url)"
+      fi
+      LOCAL_REPO_NAME="$(_repo_name "$LOCAL_REPO_URL")"
+      SOURCE_REPO_NAME="$(_repo_name "$REPO_NAME")"
+
+      if [[ "$LOCAL_REPO_NAME" == "$SOURCE_REPO_NAME" ]]; then
+        _note "You seem to be sourcing your local files remotely."
+        cat <<EOF
+$(_rc_file_line_reference)
+
+You can remove "$REPO_NAME" when sourcing from your local dotfiles repo (${FRESH_LOCAL/#$HOME/~}).
+Use \`fresh file\` instead of \`fresh $REPO_NAME file\`.
+
+To disable this warning, add \`FRESH_NO_LOCAL_CHECK=true\` in your freshrc file.
+
+EOF
+        FRESH_NO_LOCAL_CHECK=1
+      fi
+    fi
+
     local REPO_DIR="$FRESH_PATH/source/$(_repo_name "$REPO_NAME")"
     mkdir -p "$(dirname "$REPO_DIR")"
     if ! [ -e "$REPO_DIR" ]; then
@@ -645,13 +667,19 @@ _confirm() {
   esac
 }
 
-_fatal_error() {
-  echo $'\033[4;31mError\033[0m:' "$1" >&2
+_rc_file_line_reference() {
   if [[ "$IN_RC_FILE" == 1 ]]; then
     local DISPLAY_RC_FILE="${RC_FILE/#$HOME/~}"
     local RC_CONTENT="$(head -$RC_LINE "$RC_FILE" | tail -1)"
+    echo "$DISPLAY_RC_FILE:$RC_LINE: $RC_CONTENT"
+  fi
+}
+
+_fatal_error() {
+  echo $'\033[4;31mError\033[0m:' "$1" >&2
+  if [[ "$IN_RC_FILE" == 1 ]]; then
     cat >&2 <<EOF
-$DISPLAY_RC_FILE:$RC_LINE: $RC_CONTENT
+$(_rc_file_line_reference)
 
 You may need to run \`fresh update\` if you're adding a new line,
 or the file you're referencing may have moved or been deleted.
