Add colourful success/error messages.
Closes #27.

diff --git a/bin/fresh b/bin/fresh
--- a/bin/fresh
+++ b/bin/fresh
@@ -19,17 +19,13 @@ fresh_install() {
 
   # safety check to ensure the user doesn't lock themselves out
   if [[ -z "$FRESH_NO_BIN_CHECK" ]] && [[ ! -x "$FRESH_PATH/build.new/bin/fresh" ]]; then
-    cat >&2 <<EOF
-Error: It looks you do not have fresh in your freshrc file.
-This could result in difficulties running \`fresh\` later.
-
-You probably want to add a line like the following using \`fresh edit\`:
+    _fatal_error "It looks you do not have fresh in your freshrc file. This could result
+in difficulties running \`fresh\` later. You probably want to add a line like
+the following using \`fresh edit\`:
 
   fresh freshshell/fresh bin/fresh --bin
 
-To disable this error, add \`FRESH_NO_BIN_CHECK=true\` in your freshrc file.
-EOF
-    return 1
+To disable this error, add \`FRESH_NO_BIN_CHECK=true\` in your freshrc file."
   fi
 
   # output files should be read-only
@@ -41,7 +37,7 @@ EOF
 
   if [ ! "$1" == "--quiet" ];
   then
-    echo Your dot files are now fresh.
+    echo $'Your dot files are now \033[1;32mfresh\033[0m.'
   fi
 }
 
@@ -328,7 +324,7 @@ EOF
 }
 
 _fatal_error() {
-  echo "$1" >&2
+  echo $'\033[4;31mError\033[0m:' "$1" >&2
   exit 1
 }
 
