Fix typo in error message.

diff --git a/bin/fresh b/bin/fresh
--- a/bin/fresh
+++ b/bin/fresh
@@ -36,7 +36,7 @@ fresh() {
   fi
 
   if [[ $(find "$SOURCE_DIR" -path "$SOURCE_DIR/$FILE_NAME" | wc -l) -lt 1 ]]; then
-    echo "Could not find \"$FILE_NAME\" source file. 2>&1" >&2
+    echo "Could not find \"$FILE_NAME\" source file." >&2
     exit 1
   fi
 
